version: '3.4'
networks:
  backend:
  frontend:

services:
  eventcatalaogapi:
    build:
      context: .\EventCatalaogAPI
      dockerfile: Dockerfile
    image: eventcatalaogapi
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalogdb
      DatabaseUserName: sa
      DatabaseUserPassword: Events(!)
      ExternalEventCatalogBaseUrl: http://localhost:5010
    container_name: eventcatalog
    ports:
      - "5010:80"
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Events(!)
    container_name: Eventcatalogdb
    ports:
      - "1447:1433"
    networks:
      - backend
  
  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MVc_Client: http://localhost:5200
      BasketApiClient: http://localhost:5051
    container_name: tokenserverdb
    ports:
      - "5020:80"
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventCatalogUrl: http://eventcatalaogapi
      IdentityUrl: http://10.0.0.66:5020
      CallBackUrl: http://localhost:5200
      CartUrl: http://cartapi
    container_name: WebShop 
    ports:
      - "5200:80"
    networks:
      - frontend
    depends_on:
      - eventcatalaogapi
      - tokenserver


 